apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen12d-sep17-1
  janus-idp.io/tekton: codegen12d-sep17-1
  backstage.io/kubernetes-id: codegen12d-sep17-1
  backstage.io/kubernetes-namespace: codegen12d-sep17-1 
  app.kubernetes.io/part-of: codegen12d-sep17-1
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/
