---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: codegen12d-sep17-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen12d-sep17-1 
  name: codegen12d-sep17-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi